export interface ZipEntry {
    path: string;
    name: string;
    isDirectory: boolean;
    size: number;
    compressedSize: number;
    lastModified: Date;
}

export interface TreeNode {
    name: string;
    path: string;
    isDirectory: boolean;
    entry?: ZipEntry;
    children: TreeNode[];
    isExpanded?: boolean;
}

export interface ZipState {
    status: "idle" | "loading" | "loaded" | "error";
    fileName: string;
    totalSize: number;
    entries: ZipEntry[];
    tree: TreeNode;
    error: string | null;
    loadMethod: "file" | "url" | null;
    supportsRangeRequests: boolean;
    progress: number; // 0 - 100
    progressMessage: string;
}

export interface PreviewState {
    status: "idle" | "loading" | "loaded" | "error";
    entry: ZipEntry | null;
    type: PreviewType;
    content: string | null;
    blobUrl: string | null;
    error: string | null;
}

export type PreviewType =
    | "image"
    | "text"
    | "code"
    | "video"
    | "audio"
    | "pdf"
    | "font"
    | "document"
    | "spreadsheet"
    | "presentation"
    | "unsupported";

export const FILE_SIZE_LIMITS = {
    UPLOAD: 4 * 1024 * 1024 * 1024, // 4GB (drag & drop — browser memory is the real limit)
    URL: 4 * 1024 * 1024 * 1024, // 4GB (URL fetch — browser memory is the real limit)
    PREVIEW: 50 * 1024 * 1024, // 50MB per file preview
} as const;

export const EXTENSION_MAP: Record<string, PreviewType> = {
    // Images
    ".png": "image",
    ".jpg": "image",
    ".jpeg": "image",
    ".gif": "image",
    ".svg": "image",
    ".webp": "image",
    ".bmp": "image",
    ".ico": "image",
    ".avif": "image",

    // Video
    ".mp4": "video",
    ".webm": "video",
    ".mov": "video",
    ".avi": "video",
    ".mkv": "video",
    ".flv": "video",
    ".wmv": "video",
    ".m4v": "video",
    ".3gp": "video",
    ".3g2": "video",
    ".mpg": "video",
    ".mpeg": "video",

    // Audio
    ".mp3": "audio",
    ".wav": "audio",
    ".flac": "audio",
    ".aac": "audio",
    ".m4a": "audio",
    ".ogg": "audio",
    ".oga": "audio",
    ".opus": "audio",
    ".wma": "audio",
    ".aiff": "audio",
    ".aif": "audio",
    ".mid": "audio",
    ".midi": "audio",
    ".amr": "audio",
    ".pcm": "audio",

    // PDF
    ".pdf": "pdf",

    // Documents (Office Open XML & legacy)
    ".docx": "document",
    ".doc": "document",
    ".odt": "document",
    ".rtf": "document",
    ".pages": "document",

    // Spreadsheets
    ".xlsx": "spreadsheet",
    ".xls": "spreadsheet",
    ".ods": "spreadsheet",
    ".csv": "spreadsheet",
    ".tsv": "spreadsheet",
    ".numbers": "spreadsheet",

    // Presentations
    ".pptx": "presentation",
    ".ppt": "presentation",
    ".odp": "presentation",
    ".key": "presentation",

    // Code
    ".js": "code",
    ".jsx": "code",
    ".ts": "code",
    ".tsx": "code",
    ".py": "code",
    ".rb": "code",
    ".go": "code",
    ".rs": "code",
    ".java": "code",
    ".kt": "code",
    ".kts": "code",
    ".swift": "code",
    ".c": "code",
    ".cpp": "code",
    ".cc": "code",
    ".cxx": "code",
    ".h": "code",
    ".hpp": "code",
    ".hxx": "code",
    ".cs": "code",
    ".php": "code",
    ".lua": "code",
    ".r": "code",
    ".sql": "code",
    ".sh": "code",
    ".bash": "code",
    ".zsh": "code",
    ".fish": "code",
    ".ps1": "code",
    ".bat": "code",
    ".cmd": "code",
    ".html": "code",
    ".htm": "code",
    ".css": "code",
    ".scss": "code",
    ".sass": "code",
    ".less": "code",
    ".vue": "code",
    ".svelte": "code",
    ".astro": "code",
    ".yaml": "code",
    ".yml": "code",
    ".toml": "code",
    ".ini": "code",
    ".cfg": "code",
    ".conf": "code",
    ".dockerfile": "code",
    ".graphql": "code",
    ".gql": "code",
    ".proto": "code",
    ".tex": "code",
    ".bib": "code",
    ".sty": "code",
    ".cls": "code",
    ".ltx": "code",
    // Additional languages
    ".dart": "code",
    ".scala": "code",
    ".sc": "code",
    ".clj": "code",
    ".cljs": "code",
    ".cljc": "code",
    ".edn": "code",
    ".ex": "code",
    ".exs": "code",
    ".erl": "code",
    ".hrl": "code",
    ".hs": "code",
    ".lhs": "code",
    ".ml": "code",
    ".mli": "code",
    ".fs": "code",
    ".fsx": "code",
    ".fsi": "code",
    ".pl": "code",
    ".pm": "code",
    ".t": "code",
    ".m": "code",
    ".mm": "code",
    ".groovy": "code",
    ".gvy": "code",
    ".gradle": "code",
    ".v": "code",
    ".sv": "code",
    ".vhd": "code",
    ".vhdl": "code",
    ".d": "code",
    ".nim": "code",
    ".nims": "code",
    ".zig": "code",
    ".cr": "code",
    ".jl": "code",
    ".elm": "code",
    ".purs": "code",
    ".rkt": "code",
    ".scm": "code",
    ".ss": "code",
    ".lisp": "code",
    ".cl": "code",
    ".el": "code",
    ".cmake": "code",
    ".makefile": "code",
    ".mk": "code",
    ".mak": "code",
    ".asm": "code",
    ".s": "code",
    ".nasm": "code",
    ".wasm": "code",
    ".wat": "code",
    ".tf": "code",
    ".hcl": "code",
    ".nix": "code",
    ".dhall": "code",
    ".jsonc": "code",
    ".json5": "code",
    ".jsonl": "code",
    ".plist": "code",
    ".erb": "code",
    ".ejs": "code",
    ".hbs": "code",
    ".mustache": "code",
    ".pug": "code",
    ".jade": "code",
    ".haml": "code",
    ".slim": "code",
    ".twig": "code",
    ".liquid": "code",
    ".njk": "code",
    ".styl": "code",
    ".postcss": "code",
    ".glsl": "code",
    ".hlsl": "code",
    ".wgsl": "code",
    ".frag": "code",
    ".vert": "code",
    ".comp": "code",
    ".sol": "code",
    ".vy": "code",
    ".move": "code",
    ".cob": "code",
    ".cbl": "code",
    ".f": "code",
    ".f90": "code",
    ".f95": "code",
    ".f03": "code",
    ".pas": "code",
    ".pp": "code",
    ".dpr": "code",
    ".ada": "code",
    ".adb": "code",
    ".ads": "code",
    ".cue": "code",
    ".prisma": "code",
    ".thrift": "code",
    ".avdl": "code",
    ".capnp": "code",
    ".flatbuffers": "code",
    ".fbs": "code",
    ".smithy": "code",
    ".pkl": "code",

    // Text
    ".txt": "text",
    ".md": "text",
    ".mdx": "text",
    ".json": "code",
    ".xml": "code",
    ".log": "text",
    ".env": "text",
    ".gitignore": "text",
    ".editorconfig": "text",
    ".prettierrc": "code",
    ".eslintrc": "code",

    // Font
    ".woff": "font",
    ".woff2": "font",
    ".ttf": "font",
    ".otf": "font",
    ".eot": "font",
};

export const LANGUAGE_MAP: Record<string, string> = {
    ".js": "javascript",
    ".jsx": "javascript",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".py": "python",
    ".rb": "ruby",
    ".go": "go",
    ".rs": "rust",
    ".java": "java",
    ".kt": "kotlin",
    ".kts": "kotlin",
    ".swift": "swift",
    ".c": "c",
    ".cpp": "cpp",
    ".cc": "cpp",
    ".cxx": "cpp",
    ".h": "c",
    ".hpp": "cpp",
    ".hxx": "cpp",
    ".cs": "csharp",
    ".php": "php",
    ".lua": "lua",
    ".r": "r",
    ".sql": "sql",
    ".sh": "bash",
    ".bash": "bash",
    ".zsh": "bash",
    ".fish": "shell",
    ".ps1": "powershell",
    ".bat": "dos",
    ".cmd": "dos",
    ".html": "html",
    ".htm": "html",
    ".css": "css",
    ".scss": "scss",
    ".sass": "scss",
    ".less": "less",
    ".json": "json",
    ".jsonc": "json",
    ".json5": "json",
    ".jsonl": "json",
    ".xml": "xml",
    ".plist": "xml",
    ".yaml": "yaml",
    ".yml": "yaml",
    ".toml": "ini",
    ".ini": "ini",
    ".cfg": "ini",
    ".conf": "ini",
    ".md": "markdown",
    ".mdx": "markdown",
    ".graphql": "graphql",
    ".gql": "graphql",
    ".proto": "protobuf",
    ".vue": "xml",
    ".svelte": "xml",
    ".astro": "xml",
    ".dockerfile": "dockerfile",
    ".tex": "latex",
    ".bib": "bibtex",
    ".sty": "latex",
    ".cls": "latex",
    ".ltx": "latex",
    // Additional languages
    ".dart": "dart",
    ".scala": "scala",
    ".sc": "scala",
    ".clj": "clojure",
    ".cljs": "clojure",
    ".cljc": "clojure",
    ".edn": "clojure",
    ".ex": "elixir",
    ".exs": "elixir",
    ".erl": "erlang",
    ".hrl": "erlang",
    ".hs": "haskell",
    ".lhs": "haskell",
    ".ml": "ocaml",
    ".mli": "ocaml",
    ".fs": "fsharp",
    ".fsx": "fsharp",
    ".fsi": "fsharp",
    ".pl": "perl",
    ".pm": "perl",
    ".t": "perl",
    ".m": "objectivec",
    ".mm": "objectivec",
    ".groovy": "groovy",
    ".gvy": "groovy",
    ".gradle": "groovy",
    ".v": "verilog",
    ".sv": "verilog",
    ".vhd": "vhdl",
    ".vhdl": "vhdl",
    ".d": "d",
    ".nim": "nim",
    ".nims": "nim",
    ".zig": "zig",
    ".cr": "crystal",
    ".jl": "julia",
    ".elm": "elm",
    ".purs": "haskell",
    ".rkt": "scheme",
    ".scm": "scheme",
    ".ss": "scheme",
    ".lisp": "lisp",
    ".cl": "lisp",
    ".el": "lisp",
    ".cmake": "cmake",
    ".makefile": "makefile",
    ".mk": "makefile",
    ".mak": "makefile",
    ".asm": "x86asm",
    ".s": "x86asm",
    ".nasm": "x86asm",
    ".wasm": "wasm",
    ".wat": "wasm",
    ".tf": "hcl",
    ".hcl": "hcl",
    ".nix": "nix",
    ".erb": "erb",
    ".ejs": "ejs",
    ".hbs": "handlebars",
    ".mustache": "handlebars",
    ".pug": "pug",
    ".jade": "pug",
    ".haml": "haml",
    ".twig": "twig",
    ".styl": "stylus",
    ".glsl": "glsl",
    ".hlsl": "hlsl",
    ".frag": "glsl",
    ".vert": "glsl",
    ".comp": "glsl",
    ".sol": "solidity",
    ".cob": "cobol",
    ".cbl": "cobol",
    ".f": "fortran",
    ".f90": "fortran",
    ".f95": "fortran",
    ".f03": "fortran",
    ".pas": "delphi",
    ".pp": "delphi",
    ".dpr": "delphi",
    ".ada": "ada",
    ".adb": "ada",
    ".ads": "ada",
    ".prisma": "graphql",
    ".thrift": "thrift",
};

export const MIME_MAP: Record<string, string> = {
    // Images
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".gif": "image/gif",
    ".svg": "image/svg+xml",
    ".webp": "image/webp",
    ".bmp": "image/bmp",
    ".ico": "image/x-icon",
    ".avif": "image/avif",

    // Video
    ".mp4": "video/mp4",
    ".webm": "video/webm",
    ".ogg": "video/ogg",
    ".mov": "video/quicktime",
    ".avi": "video/x-msvideo",
    ".mkv": "video/x-matroska",
    ".flv": "video/x-flv",
    ".wmv": "video/x-ms-wmv",
    ".m4v": "video/x-m4v",
    ".3gp": "video/3gpp",
    ".3g2": "video/3gpp2",
    ".mpg": "video/mpeg",
    ".mpeg": "video/mpeg",

    // Audio
    ".mp3": "audio/mpeg",
    ".wav": "audio/wav",
    ".flac": "audio/flac",
    ".aac": "audio/aac",
    ".m4a": "audio/mp4",
    ".oga": "audio/ogg",
    ".opus": "audio/opus",
    ".wma": "audio/x-ms-wma",
    ".aiff": "audio/aiff",
    ".aif": "audio/aiff",
    ".mid": "audio/midi",
    ".midi": "audio/midi",
    ".amr": "audio/amr",
    ".pcm": "audio/pcm",

    // PDF
    ".pdf": "application/pdf",

    // Documents
    ".docx":
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    ".doc": "application/msword",
    ".odt": "application/vnd.oasis.opendocument.text",
    ".rtf": "application/rtf",
    ".pages": "application/vnd.apple.pages",

    // Spreadsheets
    ".xlsx":
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    ".xls": "application/vnd.ms-excel",
    ".ods": "application/vnd.oasis.opendocument.spreadsheet",
    ".csv": "text/csv",
    ".tsv": "text/tab-separated-values",
    ".numbers": "application/vnd.apple.numbers",

    // Presentations
    ".pptx":
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    ".ppt": "application/vnd.ms-powerpoint",
    ".odp": "application/vnd.oasis.opendocument.presentation",
    ".key": "application/vnd.apple.keynote",

    // Fonts
    ".woff": "font/woff",
    ".woff2": "font/woff2",
    ".ttf": "font/ttf",
    ".otf": "font/otf",
};
